name: flutter_i18n_example
description: The flutter i18n example
version: 0.1.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_i18n:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # https://pub.dev/packages/devicelocale
  devicelocale: ^0.2.0
  # https://pub.dev/packages/flutter_arc_speed_dial
  flutter_arc_speed_dial: ^1.0.2
  # https://pub.dev/packages/country_icons
  country_icons: ^1.1.1
  # https://pub.dev/packages/flutter_markdown
  # Note: use `any` to prevent the error `requires SDK version <2.0.0, version solving failed`
  ## https://github.com/flutter/flutter/issues/21421#issuecomment-526292491
  #flutter_markdown: any
  # https://pub.dev/packages/flutter_html
  #flutter_html: ^0.11.0
  # https://pub.dev/packages/flutter_highlight
  #flutter_highlight: ^0.5.0

flutter:
  uses-material-design: true

  assets:
    #- assets/i18n/default.yaml
    #- assets/i18n/page.yaml
    # Or just specify the i18n directory (needs to end with `/`)
    - assets/i18n/
    - assets/i18n/example/
