name: flutter_i18n_example
description: The flutter i18n example
version: 0.1.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_i18n:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # https://pub.dev/packages/intl
  # https://api.flutter.dev/flutter/intl/intl-library.html
  intl: ^0.15.8
  # https://pub.dev/packages/flutter_arc_speed_dial
  flutter_arc_speed_dial: ^1.0.2
  # https://pub.dev/packages/country_icons
  country_icons: ^1.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/default.yaml
    - assets/i18n/page.yaml
