name: flutter_i18n
description: A flutter internationalization plugin.
version: 0.1.0
author: flytreeleft <flytreeleft@crazydan.org>
homepage: https://github.com/flytreeleft/flutter_i18n

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/yaml
  yaml: ^2.2.0
  # https://pub.dev/packages/http
  http: ^0.12.0+2
  # https://pub.dev/packages/mustache
  ## Note: using mustache will cause error:
  ##   import of dart:mirrors is not supported in the current Dart runtime
  ## so replace it with reflected_mustache
  #mustache: ^1.1.1
  # https://pub.dev/packages/reflected_mustache
  reflected_mustache: ^1.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  # https://pub.dev/packages/test
  test: ^1.9.4

flutter:
